### ISSUE TITLE
joints/vertices detected

### ISSUE THREAD

**Issue by Arnav-Purushotam** [xuxy09/RSC-Net#11]
Hi,
i used your model to scan a low res image of a person for joints
it returned the following joints:

print(joints)
[[-6.04124069e-02 -7.58821130e-01 -1.36030287e-01]
 [ 6.64194077e-02 -7.22911358e-01 -1.27670541e-03]
 [-7.00186044e-02 -6.70804858e-01  8.52521062e-02]
 [-1.71616733e-01 -4.77660120e-01  9.67647880e-02]
 [-1.14487618e-01 -5.75384080e-01 -9.08450782e-02]
 [ 2.02057883e-01 -6.65608585e-01 -8.79856050e-02]
 [ 3.34627986e-01 -4.87401307e-01 -1.36859328e-01]
 [ 1.40230328e-01 -4.98071045e-01 -2.29404062e-01]
 [-4.13627969e-03 -2.36514777e-01  1.82570945e-02]
 [-7.99493119e-02 -1.72764868e-01  4.19234037e-02]
 [-3.04055244e-01 -4.19897437e-02 -1.56800151e-01]
 [-1.95208192e-01  1.82137489e-01  5.87285310e-02]
 [ 1.65932719e-02 -1.39060929e-01 -1.17385648e-02]
 [-1.18877657e-01  4.24312949e-02 -2.33635023e-01]
 [-1.03444241e-01  2.48754814e-01  2.34296471e-02]
 [-7.78085738e-02 -8.01025391e-01 -9.89653692e-02]
 [-3.36936563e-02 -8.10274601e-01 -1.45270944e-01]
 [-4.43344414e-02 -8.19930434e-01 -7.00204819e-03]
 [ 5.31038344e-02 -8.41723680e-01 -1.07568718e-01]
 [-2.00364143e-01  3.71141195e-01 -5.49159050e-02]
 [-1.26811206e-01  3.74223828e-01 -3.79313231e-02]
 [-6.84206337e-02  2.40866959e-01  7.32095838e-02]
 [-2.68898785e-01  3.15093815e-01 -3.10784578e-02]
 [-2.90248752e-01  2.87368000e-01  4.05772030e-02]
 [-1.62859082e-01  1.79714262e-01  1.14852905e-01]
 [-1.95208192e-01  1.82137489e-01  5.87285310e-02]
 [-3.04055244e-01 -4.19897437e-02 -1.56800151e-01]
 [-8.81563351e-02 -2.82877415e-01  8.54171440e-02]
 [ 1.01012930e-01 -2.23942950e-01 -3.15033905e-02]
 [-1.18877657e-01  4.24312949e-02 -2.33635023e-01]
 [-1.03444241e-01  2.48754814e-01  2.34296471e-02]
 [-1.14487618e-01 -5.75384080e-01 -9.08450782e-02]
 [-1.71616733e-01 -4.77660120e-01  9.67647880e-02]
 [-7.00186044e-02 -6.70804858e-01  8.52521062e-02]
 [ 2.02057883e-01 -6.65608585e-01 -8.79856050e-02]
 [ 3.34627986e-01 -4.87401307e-01 -1.36859328e-01]
 [ 1.40230328e-01 -4.98071045e-01 -2.29404062e-01]
 [ 5.61497957e-02 -7.20549762e-01 -1.31271025e-02]
 [-5.81591874e-02 -9.40906048e-01 -9.45677161e-02]
 [ 1.30820684e-02 -2.47979790e-01  4.07510623e-02]
 [ 6.94963410e-02 -6.79624557e-01 -8.00156035e-04]
 [ 7.99441785e-02 -4.94875371e-01  3.82016413e-02]
 [-1.68672577e-03 -7.64190912e-01 -8.66440311e-02]
 [-2.71644648e-02 -8.91248465e-01 -7.28784502e-02]
 [-6.04124069e-02 -7.58821130e-01 -1.36030287e-01]
 [-3.36936563e-02 -8.10274601e-01 -1.45270944e-01]
 [-7.78085738e-02 -8.01025391e-01 -9.89653692e-02]
 [ 5.31038344e-02 -8.41723680e-01 -1.07568718e-01]
 [-4.43344414e-02 -8.19930434e-01 -7.00204819e-03]]

my doubt is:
which of these co-ordinates corresponds to a particular body part
as in right_knee, left_knee, elbow, etc
Thank you!

**Comment by xuxy09** [comment]
Hi, I am not sure how you get the joints. But most of the related information is provided here: https://github.com/xuxy09/RSC-Net/blob/master/constants.py

**Comment by Arnav-Purushotam** [comment]
Thank you!
