### ISSUE TITLE
No module named 'utils.data_loader'

### ISSUE THREAD

**Issue by nessessence** [xuxy09/RSC-Net#2]
I have already followed all the setup instruction.
when I ran this command:   python demo.py --checkpoint=./pretrained/RSC-Net.pt --img_path=./examples/im1.png
I got the output:    No module named 'utils.data_loader'

**Comment by xuxy09** [comment]
Thanks for letting me know. I have made some updates. Please try again.

**Comment by nessessence** [comment]
ModuleNotFoundError: No module named 'models.nt_xent' 
I also notice that "feat_queue" is missing in "models folder", as well.

**Comment by xuxy09** [comment]
How about now?

**Comment by nessessence** [comment]
I can run "python demo.py --checkpoint=./pretrained/RSC-Net.pt --img_path=./examples/im1.png" now. 
And got 2 output with different views. Thanks for the fast response.
I still wonder how can I get 3D human representation file after inferencing.

**Comment by xuxy09** [comment]
The output vertices are https://github.com/xuxy09/RSC-Net/blob/ce72ce50afaa37188072f84dd9382b2c68c1b5c7/demo.py#L68.
It is a PyTorch Tensor, and you can save it with pickle or numpy.

**Comment by nessessence** [comment]
thanks!
